### ISSUE TITLE
Feature - Block/Item Pallete

### ISSUE THREAD

**Issue by DaanV2** [Mojang/bedrock-samples#13]
Would it be possible to add a `gen` folder where Minecraft exports its block and item palette to as json?

This would be very useful for developing tools 😄

**Comment by mammerla** [comment]
Should be added now - check out https://github.com/Mojang/bedrock-samples/tree/preview/metadata.  I expect the formats might get tweaked, but LMK if you have feedback.

**Comment by DaanV2** [comment]
All look F**** Amazing, god I can throw away so much handwritten stuff 😄 

# Vanilla data

**Items**
- maximum damage value? If applicable
