### ISSUE TITLE
item_texture.json, terrain_texture.json not updated for 1.20

### ISSUE THREAD

**Issue by 7UKECREAT0R** [Mojang/bedrock-samples#30]
The following files are missing all 1.20 related content including, but not limited to: cherry wood blocks/items, pots, pottery shards, smithing templates, armor trims, suspicious sand/gravel, etc...
- `resource_pack/textures/item_texture.json`
- `resource_pack/textures/terrain_texture.json`
- `resource_pack/textures/flipbook_textures.json`

It would be nice to have this data completed/kept up to date for the purpose of tooling that utilizes its contents.

**Comment by CRxFT** [comment]
Missing definitions for a majority of spawn eggs as well.

**Comment by mammerla** [comment]
Should now be fixed, I believe.
