### ISSUE TITLE
There is no Crafter item in my Beta Bedrock world

### ISSUE THREAD

**Issue by skanda890** [Mojang/bedrock-samples#34]
There is no Crafter item in my Mobile Beta Bedrock world. I have the latest version 1.20.60.20, is that the latest version in the beta? Is this the correct repository to raise this issue?

**Comment by skanda890** [comment]
Should I give a screenshot?

**Comment by skanda890** [comment]
Is this the correct repository to raise this issue?

**Comment by dwaneivan** [comment]
Have you turned the experiments option "Update 1.21" on?

For gameplay issue you create tickets on this site:
https://bugs.mojang.com/projects/MCPE/issues

**Comment by dwaneivan** [comment]
This is a great tutorial for that.

https://www.youtube.com/watch?v=YmMjqGPmgsA
