### ISSUE TITLE
Texture files wrong?

### ISSUE THREAD

**Issue by LeftCorpseArm** [Mojang/bedrock-samples#37]
When trying to find the Phantom, Endermen, and Dragon textures, the files showed up as .tga
I have no idea if there are others like this or if these mobs just can't be re-textured for any reason, but if you could please either guide me if I'm being stupid, or fix this if I caught something, it would be greatly appreciated.

**Comment by dwaneivan** [comment]
those are .tga or Truevision TGA Files, and yes, they can be retextured.

Watch this video for more information.
https://www.youtube.com/watch?v=MV_Pitb7G1U

If this comment solves your question, you may now close it.

**Comment by LeftCorpseArm** [comment]
Thank you!
