### ISSUE TITLE
item_texture.json and terrain_texture.json was replaced instead of being merged (1.20.70)

### ISSUE THREAD

**Issue by NSPC911** [Mojang/bedrock-samples#43]
Not sure how the mistake appeared, but in the [latest release](https://github.com/Mojang/bedrock-samples/releases/tag/v1.20.70.6), the item_texture.json and terrain_texture.json had decreased in file size drastically. Looking via GitLens (it doesn't show up on blame), I saw this for item_texture.json:

![image](https://github.com/Mojang/bedrock-samples/assets/87571998/18e7f8e0-a9d0-455e-a0b6-dcd9262d5b40)

My suspicion is that instead of merging with the main branch, it replaced it, so the older code was gone and the new items are left. I hope this gets fixed in 1.20.80.

**Comment by NSPC911** [comment]
I can attempt to open a Pull Request to fix this, but highly doubt that it will be merged

**Comment by NSPC911** [comment]
Fixed it in #44

**Comment by mammerla** [comment]
Sorry for the delay in getting to this. I have a PR of this fix that I built out using my updated process (for preview) at https://github.com/Mojang/bedrock-samples/pull/48, with the intent to merge this in for main/preview branches soon.. LMK if you have feedback.

**Comment by NSPC911** [comment]
Fixed in #48 , closed issue
