### ISSUE TITLE
PT-BR missing translation

### ISSUE THREAD

**Issue by eliaswolfy** [Mojang/bedrock-samples#55]
![Screenshot_20240611_210506_Minecraft](https://github.com/Mojang/bedrock-samples/assets/92587199/09a621e9-56e5-40dd-8a42-5a9f4633f498)

**Comment by mammerla** [comment]
This might be better off as a bug, maybe reported through bugs.mojang.com? thanks!

**Comment by eliaswolfy** [comment]
OK, sorry for the inconvenience 😊
