### ISSUE TITLE
No available pack for current Minecraft Bedrock version (1.21.2)

### ISSUE THREAD

**Issue by ZwhatMC** [Mojang/bedrock-samples#61]
In the "latest release" of bedrock-samples _1.21.0.3_ the sample resources are seemingly imcompatible (technically unusable at the least) with the latest version of Minecraft Bedrock _1.21.2_, while working perfectly on Minecraft preview _1.21.20.22_

I suppose there may not be a fix, as I may be misunderstanding this repo or it's contents.
If there is another way to obtain a working resource pack for 1.21.2, guidence would be greatly appreciated.

**Comment by mammerla** [comment]
1.21.2 should "just" be a hotfix release of 1.21.0 (https://feedback.minecraft.net/hc/en-us/articles/28105668043661-Minecraft-1-21-2-Bedrock) and the 1.21.0 assets should work in 1.21.2 - is there a specific error or issue you are seeing?

**Comment by ZwhatMC** [comment]
I assume I must have the wrong version of the samples then, instead of v1.21.0.3, which sample version should be used?
Thank you for the response.

**Comment by mammerla** [comment]
You should be able to use the "main" release of 1.21.0 to support version 1.21.2

**Comment by ZwhatMC** [comment]
Sorry if I happen to be missing it, but I couldn't find the bedrock-samples v1.21.0. The closest I found was 1.21.0.20-Preview.

Anyway, I appreciate your willingness to help. It's great to know that the community's issues are being heard. I've found a workaround for the issue I was facing, so I no longer need a solution, but thank you again.

**Comment by mammerla** [comment]
OK, thanks. I think I meant that https://github.com/Mojang/bedrock-samples/releases/tag/v1.21.0.3 should work for version 1.21.2 but sounds like you've resolved the issue :)
