### ISSUE TITLE
Versioning clarity in the manifest for Modules in Behavior Packs

### ISSUE THREAD

**Issue by Visual1mpact** [Mojang/bedrock-samples#65]
https://github.com/Mojang/bedrock-samples/blob/9fc3046e86a8316bfe71948652392433398c1334/behavior_pack/manifest.json#L15

I have noticed that the versions is formatted as [0, 0, 1] in this repository but the documentation shows it as [1, 0, 0]. You can check [here](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest?view=minecraft-bedrock-stable). My question is, does it matter and if it does, can we get one or the other corrected to prevent confusion? Minor issue of course.

**Comment by mammerla** [comment]
Things should work if the version is 0, 0, 1 - Minecraft itself doesn't care about 0, 0, 1 vs. 1, 0, 0. 

But as a note to yourself or maybe other consumers of a pack - and maybe this is a bit fussy - we try to follow "semantic versioning rules" (semver.org) A major version 0 indicates this is "pre production"/beta. So yeah, I think as a matter of just trying to signal the right things, if the manifest.json you use is part of a non-beta/"production" ready to play game, you'd want to use 1,0,0 or higher. But again, I don't think it matters to Minecraft itself whether it's 0,0,1 or 1,0,0.

**Comment by Visual1mpact** [comment]
Sounds good. I can confirm that the Minecraft application doesn't care which side of the coin it's on. Just wanted to make sure there was some clarity with regards to the differences between the two sources. I'll go ahead and close this. Thanks for the response and keep up the good work - team included!
