### ISSUE TITLE
Missing Mob Burning Fire Texture

### ISSUE THREAD

**Issue by punctdan** [Mojang/bedrock-samples#67]
Bedrock samples is missing this fire texture. I tried changing fire_0.png, fire_1.png and campfire.png texture files but they do not affect this texture. I checked everywhere but I could not find this texture anywhere.

![image](https://github.com/user-attachments/assets/eba634c0-4a7f-4ec1-8c04-0ba7ce83b8ba)

**Comment by TheodoreMeyer** [comment]
The location is at https://github.com/Mojang/bedrock-samples/blob/main/resource_pack/textures/flame_atlas.png

Tested it in game to double check.

**Comment by punctdan** [comment]
Thank you, this works. It even applies to blaze when it is charged. Closing the issue.
