### ISSUE TITLE
No 1.20 features?

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [Mojang/bedrock-samples#7]
I downloaded the resource pack template, and to my surprise, there aren't any of the 1.20 features such as bamboo blocks and hanging signs. No camels either.

**Comment by InternetLizard** [comment]
I was considering posting about this, but I decided to just give them some more time to add them. It's been two months. Instead, they've taken away some textures and models.

**Comment by mammerla** [comment]
We don't plan to add the assets for the experimental ones for as long as they are in experiments/experimental development, in part because they might undergo more rapid iteration (e.g., their model changes) and that could strand some content - LMK if that is a larger issue.

**Comment by grimsteel** [comment]
If you have the Bedrock Preview installed on Windows 10/11, you can find the latest packs in `C:\Program Files\WindowsApps\Microsoft.MinecraftWindowsBeta_VERSION_x64__8wekyb3d8bbwe\data\{resource|behavior}_packs\experimental_next_major_update`

**Comment by dwaneivan** [comment]
I believe the question has been answered this issue should be closed?
