### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Imposterwastaken1234** [Mojang/bedrock-samples#73]
I can’t seem to get it in my resource and behavior pack sections in the game itself. I have the files in the right place… how do I fix this?

**Comment by mammerla** [comment]
If you're looking to use the files in this folder directly, they're really not designed to be used as is; they are just reference sources and starters. If you want examples of "ready to run" packs, check out https://github.com/microsoft/minecraft-samples - e.g., the add-on starter sample. 

If you have customized resource packs and behavior packs are not showing up, here are some things to check:

- Are the files inside of the right development_behavior_packs/development_resource_packs folder on com.mojang (the folder path will depend based on whether you're using the main release or preview)? See https://learn.microsoft.com/minecraft/creator/documents/gettingstarted
- Are they formatted as proper JSON? Try opening the files in visual studio code and ensure there are no "red squiggly" errors
- Is the min_engine_version set correctly? (to something like [1, 21, 20] or lower.
- Do you have content error logging turned on and does that say anything? (https://learn.microsoft.com/en-us/minecraft/creator/documents/contenterrorlog)

See also Intro to Resource Packs (https://learn.microsoft.com/en-us/minecraft/creator/documents/resourcepack) and Into to Behavior Packs (https://learn.microsoft.com/en-us/minecraft/creator/documents/behaviorpack)
