### ISSUE TITLE
Missing variable declarations effecting minecart.animation

### ISSUE THREAD

**Issue by sunnobunno** [Mojang/bedrock-samples#78]
The file minecart.animation uses the following entity-level variables `variable.rail_offset` `variable.hurt` `variable.rail_rotation`.
These variables are not declared in any corresponding animation controller or other file type, and when this animation file is used in-game it throws errors. I am unable to figure out what molang queries would make them up.

Could there possibly be a missing animation controller for the minecart, or am I missing where these variables are defined?
[minecart.animation.json](https://github.com/user-attachments/files/17427151/minecart.animation.json)

**Comment by sunnobunno** [comment]
I found where `variable.hurt` is defined within minecart.entity.json. However, I still cannot find how `variable.rail_rotation` and `variable.rail_offset` are defined. Are these defined internally within bedrock that's inaccessible?

**Comment by mammerla** [comment]
For built in entities in Minecraft, sometimes these variables are declared internally in code, unfortunately, which makes discovering them more difficult (and we should add more to the docs here.) If you're creating your own entities, you can use runtime_identifier : "minecraft:minecart" to get the particular initialization behavior for these variables.

**Comment by sunnobunno** [comment]
Thank you very much for your response! I will test this out. Have a great day
